function createfigure(X1, Y1, Size1, X2, Y2, X3, Y3, X4, Size2, Color1, X5, Y4, Color2, X6, Y5, Size3, Color3, X7, Y6, X8, Y7, X9, Y8, X10, Y9, X11, Y10)
%CREATEFIGURE(X1, Y1, Size1, X2, Y2, X3, Y3, X4, Size2, Color1, X5, Y4, Color2, X6, Y5, Size3, Color3, X7, Y6, X8, Y7, X9, Y8, X10, Y9, X11, Y10)
%  X1:  vector of scatter x data
%  Y1:  vector of scatter y data
%  SIZE1:  vector of scatter size data
%  X2:  vector of scatter x data
%  Y2:  vector of scatter y data
%  X3:  vector of scatter x data
%  Y3:  vector of scatter y data
%  X4:  vector of scatter x data
%  SIZE2:  vector of scatter size data
%  COLOR1:  vector of scatter color data
%  X5:  vector of scatter x data
%  Y4:  vector of scatter y data
%  COLOR2:  vector of scatter color data
%  X6:  vector of scatter x data
%  Y5:  vector of scatter y data
%  SIZE3:  vector of scatter size data
%  COLOR3:  vector of scatter color data
%  X7:  vector of scatter x data
%  Y6:  vector of scatter y data
%  X8:  vector of scatter x data
%  Y7:  vector of scatter y data
%  X9:  vector of scatter x data
%  Y8:  vector of scatter y data
%  X10:  vector of scatter x data
%  Y9:  vector of scatter y data
%  X11:  vector of scatter x data
%  Y10:  vector of scatter y data

%  Auto-generated by MATLAB on 08-May-2025 10:13:07

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,Size1,'MarkerEdgeColor','none',...
    'MarkerFaceColor',[0.2422 0.1504 0.6603]);

% Create scatter
scatter(X2,Y2,Size1,'MarkerEdgeColor','none',...
    'MarkerFaceColor',[0.154 0.5902 0.9218]);

% Create scatter
scatter(X3,Y3,Size1,'MarkerEdgeColor','none',...
    'MarkerFaceColor',[0.5044 0.7993 0.348]);

% Create scatter
scatter(X4,X4,Size2,Color1,'MarkerEdgeColor',[0 0 0],'LineWidth',1.5,...
    'MarkerFaceColor',[0 0 0],...
    'Marker','^');

% Create scatter
scatter(X5,Y4,Size2,Color2,'MarkerEdgeColor',[0 0 0],'LineWidth',1.5,...
    'MarkerFaceColor',[1 0 0],...
    'Marker','^');

% Create text
text('Parent',axes1,'VerticalAlignment','top',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','FC',...
    'Position',[0 -15 0]);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','\bf{PU}_{tx}',...
    'Position',[-1000 1006 0]);

% Create scatter
scatter(X6,Y5,Size3,Color3,'LineWidth',2,'Marker','x');

% Create scatter
scatter(X7,Y6,Size3,Color3,'LineWidth',2,'Marker','x');

% Create scatter
scatter(X8,Y7,Size3,Color3,'LineWidth',2,'Marker','x');

% Create scatter
scatter(X9,Y8,Size1,Color3,'LineWidth',2);

% Create scatter
scatter(X10,Y9,Size1,Color3,'LineWidth',2);

% Create scatter
scatter(X11,Y10,Size1,Color3,'LineWidth',2);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','CH_{1}',...
    'Position',[258.861472066716 -245.811102932733 0]);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','CH_{2}',...
    'Position',[-542.993840841144 -309.327068384877 0]);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','CH_{3}',...
    'Position',[-203.369419297458 305.274478997642 0]);

% Create rectangle
rectangle('Parent',axes1,'Position',[-350 450 300 300],'LineWidth',1,...
    'LineStyle','--',...
    'Curvature',[1 1]);

% Create rectangle
rectangle('Parent',axes1,'Position',[550 250 300 300],'LineWidth',1,...
    'LineStyle','--',...
    'Curvature',[1 1]);

% Create rectangle
rectangle('Parent',axes1,'Position',[250 -550 300 300],'LineWidth',1,...
    'LineStyle','--',...
    'Curvature',[1 1]);

% Create rectangle
rectangle('Parent',axes1,'Position',[-150 -950 300 300],'LineWidth',1,...
    'LineStyle','--',...
    'Curvature',[1 1]);

% Create rectangle
rectangle('Parent',axes1,'Position',[-750 -250 300 300],'LineWidth',1,...
    'LineStyle','--',...
    'Curvature',[1 1]);

% Create rectangle
rectangle('Parent',axes1,'Position',[-1000 -1000 2000 2000],'LineWidth',1,...
    'Curvature',[1 1]);

% Create ylabel
ylabel('Y','FontName','Times New Roman');

% Create xlabel
xlabel('X','FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-1000 1000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1000 1000]);
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1],'FontName','Times New Roman',...
    'PlotBoxAspectRatio',[1000 1000 1]);
